# Generated by Django 4.1.7 on 2023-05-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suserreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('Sclass', models.CharField(max_length=50)),
                ('Schoolname', models.CharField(max_length=50)),
                ('board', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(max_length=10)),
            ],
        ),
    ]
