# Generated by Django 4.1.7 on 2023-05-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suserreg',
            name='phone_no',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
