# Generated by Django 4.1.7 on 2023-05-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0004_alter_suserreg_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suserreg',
            name='phone_no',
            field=models.IntegerField(),
        ),
    ]
